# Spam classifier 

In [1]:
# Importing the dataset

In [2]:
import pandas as pd

In [3]:
messages = pd.read_csv(r'C:\Users\VK\ML\NLP\Vitthal-NLP\smsspamcollection\SMSSpamCollection', sep='\t', names=["label", "message"])

In [4]:
messages.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
messages.shape

(5572, 2)

In [6]:
# Data cleaning and preporocessing

In [7]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\VK\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [8]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

In [9]:
porter = PorterStemmer()

In [10]:
wordnet = WordNetLemmatizer()

In [11]:
corpus = []

In [12]:
for i in range(0, len(messages)):
    review = re.sub("[^a-zA-Z]", ' ', messages['message'][i])
    review = review.lower()
    review = review.split()
    
    review = [wordnet.lemmatize(word) for word in review if word not in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [13]:
# Creating the BagOfWords Model

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [15]:
tfidf = TfidfVectorizer(max_features=5000)

In [16]:
X = tfidf.fit_transform(corpus)

In [17]:
X.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [18]:
type(X)

scipy.sparse.csr.csr_matrix

In [19]:
X.shape

(5572, 5000)

In [20]:
X[:,:]

<5572x5000 sparse matrix of type '<class 'numpy.float64'>'
	with 43040 stored elements in Compressed Sparse Row format>

In [21]:
y = pd.get_dummies(messages['label'], drop_first=True)

In [22]:
type(y)

pandas.core.frame.DataFrame

In [23]:
y.shape

(5572, 1)

In [24]:
y.head()

spam
0     0
1     0
2     1
3     0
4     0

In [25]:
y = y.iloc[:,]
y

spam
0        0
1        0
2        1
3        0
4        0
...    ...
5567     1
5568     0
5569     0
5570     0
5571     0

[5572 rows x 1 columns]

In [26]:
# Train Test split

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
X_tain, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)

In [29]:
# Training the model using Naive Bayes Classifier

In [30]:
from sklearn.naive_bayes import MultinomialNB

In [31]:
spam_detect_model = MultinomialNB().fit(X_tain, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [32]:
y_pred = spam_detect_model.predict(X_test)

In [33]:
y_pred

array([0, 0, 0, ..., 0, 1, 0], dtype=uint8)

In [34]:
from sklearn.metrics import confusion_matrix

In [35]:
confusion_m = confusion_matrix(y_test, y_pred)

In [36]:
confusion_m

array([[955,   0],
       [ 26, 134]], dtype=int64)

In [37]:
from sklearn.metrics import accuracy_score

In [38]:
accuracy = accuracy_score(y_test, y_pred)

In [39]:
accuracy

0.9766816143497757